version: "2"

services:
  #debugger:
  #  image: sjourdan/toolbox
  #  container_name: debugger
  #  networks:
  #    - squirrel:latest
  #  dns: 8.8.8.8
  #  command: nc -l 50070

  squirrel:
    image: adapter.squirrel:latest
    container_name: squirrel_adapter
    environment:
      - HOBBIT_RABBIT_HOST=rabbit
      - ./whitelist/whitelist.txt:/var/squirrel/whitelist.txt:ro
    command: java -cp squirrel-adapter-1.0.0.jar org.hobbit.core.run.ComponentStarter org.dice_research.squirrel.adapter.SquirrelAdapter